import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import UploadThingButton from "./_components/button";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <ClerkProvider>
        <html lang="en" data-theme="retro">
          <body className={`${GeistSans.variable}`}>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UploadThingButton
                appearance={{
                  container: "flex felx-wrap gap-8 bg-gray-800 p-4 rounded-md",
                  button: "flex felx-wrap gap-8 bg-blue-500 text-white py-2 px-4 rounded",
                  allowedContent: "flex felx-wrap gap-8 text-gray-400"
                }}
              />
              <UserButton />
            </SignedIn>
            {children}
            <div className="w-full"></div>
          </body>
        </html>
      </ClerkProvider>
  );
}
